"""added cascade delete in answer table

Revision ID: 28dca2e81e0b
Revises: b6e9f6d53309
Create Date: 2025-04-13 19:22:40.366484

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28dca2e81e0b"
down_revision: Union[str, None] = "b6e9f6d53309"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("answers_user_id_fkey", "answers", type_="foreignkey")
    op.drop_constraint("answers_topic_id_fkey", "answers", type_="foreignkey")
    op.create_foreign_key(
        None, "answers", "topics", ["topic_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "answers", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "answers", type_="foreignkey")
    op.drop_constraint(None, "answers", type_="foreignkey")
    op.create_foreign_key(
        "answers_topic_id_fkey", "answers", "topics", ["topic_id"], ["id"]
    )
    op.create_foreign_key(
        "answers_user_id_fkey", "answers", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
