"""added cascade delete in task_examples table

Revision ID: 674c63e313cd
Revises: a959d440fbe9
Create Date: 2025-04-13 20:52:26.084764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674c63e313cd'
down_revision: Union[str, None] = 'a959d440fbe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_examples_topic_id_fkey', 'task_examples', type_='foreignkey')
    op.drop_constraint('task_examples_task_type_id_fkey', 'task_examples', type_='foreignkey')
    op.create_foreign_key(None, 'task_examples', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_examples', 'task_types', ['task_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_examples', type_='foreignkey')
    op.drop_constraint(None, 'task_examples', type_='foreignkey')
    op.create_foreign_key('task_examples_task_type_id_fkey', 'task_examples', 'task_types', ['task_type_id'], ['id'])
    op.create_foreign_key('task_examples_topic_id_fkey', 'task_examples', 'topics', ['topic_id'], ['id'])
    # ### end Alembic commands ###
