"""added unique constraint on name in task_types table

Revision ID: a959d440fbe9
Revises: 080a7b0047a0
Create Date: 2025-04-13 19:27:31.199195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a959d440fbe9'
down_revision: Union[str, None] = '080a7b0047a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'task_types', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_types', type_='unique')
    # ### end Alembic commands ###
