services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
volumes:
  pgdata: